name: Build 

on:
  workflow_call:

jobs:
  build:
    permissions:
      packages: write
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: gradle
    # Set GitHub secrets as environment variables
    - name: Set GitHub Secrets
      env:
        GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    # Show the GitHub secrets (for debugging purposes, remove or comment this line later)
    - run: echo "GitHub username: $GH_USERNAME, GitHub token: $GH_TOKEN"
    # Compile with Gradle
    - name: Build with Gradle
      run: ./gradlew build --no-daemon
    # test
    - name: Test with Gradle
      run: ./gradlew test --no-daemon # Modify this line to use Gradle wrapper instead of Maven
    - run: mkdir test-results && cp build/test-results/test/*/*.xml test-results
    - uses: actions/upload-artifact@v3
      with:
        name: Application-Binary
        path: candidate-binary
    - uses: actions/upload-artifact@v3
      with:
        name: Test-Results
        path: test-results
    - name: Publish Test Results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Test Results
        path: test-results 
    - name: Download Test Results
      uses: actions/download-artifact@v2
      with:
        name: Test Results
