name: Build

on:
  workflow_call:

jobs:
  build:
    permissions:
      packages: write
      actions: read
      contents: read
      security-events: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - run: mkdir candidate-binary && cp build/libs/*.jar candidate-binary

      - name: Test with Gradle
        run: ./gradlew test --no-daemon

      - run: mkdir test-results && cp build/test-results/test/*.xml test-results

      - uses: actions/upload-artifact@v3
        with:
          name: Application-Binary
          path: candidate-binary

      - uses: actions/upload-artifact@v3
        with:
          name: Test-Results
          path: test-results

      - name: Publish Test Results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test Results
          path: test-results 

      - name: Download Test Results
        uses: actions/download-artifact@v2
        with:
          name: Test Results
