name: DAST
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  pull_request:

jobs:
  zap_scan:
    permissions:
      packages: write
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    name: OWASP ZAP
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.5.1
        with:
          token: ${{ secrets.GH_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://managed-identity-wallets.dev.demo.catena-x.net/'
  
