name: DAST
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  pull_request:

jobs:
  zap_scan:
    permissions:
      packages: write
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    name: OWASP ZAP
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        # use this for a full dast scan
        # uses: zaproxy/action-full-scan@v0.5.1
        # with:
          # token: ${{ secrets.GH_TOKEN }}
          # docker_name: 'owasp/zap2docker-stable'
          # cmd_options: '-swagger https://managed-identity-wallets-new.int.demo.catena-x.net/ui/swagger-ui/index.html'
          # target: 'https://managed-identity-wallets-new.int.demo.catena-x.net'
        # or this for an api scan
        uses: zaproxy/action-api-scan@v0.4.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          format: openapi
          #MIW:
          #target: 'https://managed-identity-wallets-new.int.demo.catena-x.net/docs/api-docs/docs
          target: '../../API Definitions/openapi_Knowledge_Agents.json'
