name: CI / CD Pipeline

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  workflow_dispatch:
  
jobs:
  service-build:
    name: service-build
    uses: ./.github/workflows/service-build.yml
    secrets: inherit #https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idsecretsinherit
 
  SAST:
    needs: service-build
    name: SAST
    uses: ./.github/workflows/SAST.yml
    secrets: inherit
