name: CI / CD Pipeline

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * 5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger Build Workflow
        uses: peter-evans/workflow-dispatch@v2
        with:
          workflow: Build.yml # Assuming Build.yml is located under .github/workflows directory
          token: ${{ secrets.GITHUB_TOKEN }}
