name: SAST

on:
  workflow_call:
  
jobs:
  CodeQL:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    
    strategy:
      fail-fast: false
      matrix:
        language: ['java']
        # CodeQL supports ['cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby']
        # Learn more about CodeQL language support at https://aka.ms/codeql-docs/language-support

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Java with version 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
          # If you wish to specify custom queries, you can do so here or in a config file.
          # By default, queries listed here will override any specified in a config file.
          # Prefix the list here with "+" to use these queries and those in the config file.
          
          # Details on CodeQL's query packs refer to : https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
          # queries: security-extended,security-and-quality

      # Build with Gradle and cache build artifacts
      - name: Build with Gradle
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: build -PgithubToken=${{ secrets.GITHUB_TOKEN }}
      - name: Cache build
        id: cache-build
        uses: actions/cache@v2
        with:
          path: ${{ env.BUILD_DIR }} # Replace this with the actual path to the build directory
          key: ${{ runner.os }}-gradle-${{ env.BUILD_DIR_HASH }}
        env:
          BUILD_DIR: './build'
          BUILD_DIR_HASH: ${{ hashFiles('**/build.gradle') }} # Hash the build.gradle file to invalidate cache if it changes
          
      # Upload build artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: ${{ env.BUILD_DIR }}/libs/*.jar # Modify the path to include the relevant build artifacts

      # Perform CodeQL Analysis
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
  
  spotbugs:
    name: SpotBugs
    needs: [CodeQL]
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    - name: Run SpotBugs action
      uses: jmservera/spotbugs-github-action@v0.1.0-alpha
      with:
        packages: com.example.-
        target: ./build/classes/java/main # Update the path to the compiled classes
        dependenciesPath: ~/.gradle/caches/modules-2/files-2.1 # Update the path to Gradle dependencies cache
        basePath: src/main/java
    - name: Upload SpotBugs report
      uses: actions/upload-artifact@v2
      with:
        name: spotbugs.sarif
        path: ${{github.workspace}}/results.sarif
    - name: Upload analysis results to GitHub Security tab
      if: always()
      uses: github/codeql-action/upload-sarif@v2.1.28
      with:
        sarif_file: ${{github.workspace}}/results.sarif
  
